### ISSUE TITLE
Having large numbers of changes seems to break the UI

### ISSUE THREAD

**Issue by jscarrott** [Piturnah/gex#1]
Just tried gex out but I had a lot of unstaged changes and the UI didn't seem to cope with the currently selected item 20-30 items off screen.

**Comment by Piturnah** [comment]
Thank you for opening this issue, the plan is to implement scrolling that follows the cursor.

Relevant: the current implementation doesn't allow you to scroll the terminal, presumably because it triggers an event and thus a redraw. Will also need to fix this.

**Comment by Piturnah** [comment]
This is (*finally*) partially addressed in a28d03a4216d269cef9da0c105854e4b0b1425c9.

I am leaving the issue open as the scrolling doesn't quite work exactly as I want it to yet. Namely -- I'd rather it keeps the entire "item" in view when scrolling down rather than just the cursor line, and when you jump to the top it should set the renderer to draw from line 1.

**Comment by Piturnah** [comment]
Fixed in 0.5 :tada:
