### ISSUE TITLE
Try gitoxide instead of git2

### ISSUE THREAD

**Issue by petr-tik** [Piturnah/gex#5]
as a user of magit, i am glad people are spreading the magic of that UI

There is an awesome project under active development that promises much faster git interactions
https://github.com/Byron/gitoxide

that has already delivered 2x performance improvements on large repos like the linux kernel
https://github.com/o2sh/onefetch/pull/635

gitoxide has a group of issues to replace git2
https://github.com/Byron/gitoxide/issues?q=is%3Aissue+is%3Aopen+label%3AC-replace-git2

I appreciate this is a personal project and git2 works fine for you now. Only wanted to make you aware in case you might find this interesting

**Comment by Piturnah** [comment]
Thanks very much for bringing this to my attention

For now I will continue using git2 due to a couple of reasons
1. I'm not keen on adding a prerequisite (cmake)
2. The build time suffers quite a lot when using gitoxide

I will potentially revisit this in the future if performance starts becoming more of an issue

![image](https://user-images.githubusercontent.com/20472367/185372773-e755d638-969d-44ab-a0b8-a446a9f5a6d5.png)
