### ISSUE TITLE
[Feature]:  On Mac allow the config file to be placed at ~/.config/gex/config.toml

### ISSUE THREAD

**Issue by LukeHalasy** [Piturnah/gex#87]
### Type of Feature

New Feature

### Description

Small change. I feel like many terminal programs for Mac take configs in the ~/.config directory (nvim, hx, etc). Provide this ability for Mac.

The `Library/Application\ Support/..` directory is tedious to type out and edit

**Comment by Piturnah** [comment]
Good to know, thanks. Never been a Mac user myself, so I just went with what this library [dirs](https://docs.rs/dirs/latest/dirs/) said was the standard for MacOS.

Would be interested to get the opinions of other Mac users, too, but since you say it is the default for programs such as neovim and helix, it sounds like a good idea to just copy that

**Comment by Piturnah** [comment]
That should do it, sorry for the wait

**Comment by Piturnah** [comment]
Released in 0.6.5 🎉
